#!/usr/bin/env bash
#
# Point the Homebrew tap at a published release.
#
# `brew install carp-dk/tap/carp` resolves to Formula/carp.rb in the
# carp-dk/homebrew-tap repository. That formula names four archives - two
# macOS, two Linux - from one GitHub release, each with the checksum the
# release itself published. This writes that file and pushes it.
#
# It is a step of its own rather than part of the release job because it can
# only run once the release exists: the URLs it writes are the release's own
# assets, and Homebrew checks every download against the sha256 beside it.
# release.yml calls it as its last act.
#
# Run it by hand for a release that predates the tap, or after a push failed:
#
#     .github/homebrew/tap.sh 0.2.1
#
# It needs `gh` signed in to read the release, and push access to the tap. In
# the workflow that arrives as HOMEBREW_TAP_TOKEN, an hour-long installation
# token from the GitHub App installed on the tap; run by hand, leave the
# variable unset and your own git credentials are used instead. Running it
# twice for one version does nothing the second time.
#
# See .github/PUBLISHING.md for the one-time setup of the tap repository.
set -euo pipefail

# `::error::` is what puts a message in the run summary under Actions. Outside
# it, the prefix is noise.
fail() {
  if [ -n "${GITHUB_ACTIONS:-}" ]; then
    echo "::error::$*" >&2
  else
    echo "error: $*" >&2
  fi
  exit 1
}

version=${1:-}
if [ -z "$version" ]; then
  echo "usage: $(basename "$0") <version>   e.g. $(basename "$0") 0.2.1" >&2
  exit 2
fi
# Accept `v0.2.1` too, since that is what the tag is called.
version=${version#v}
tag="v$version"

# Overridable so the whole thing can be rehearsed against a personal fork of
# either side without editing the script.
repo=${GITHUB_REPOSITORY:-carp-dk/carp-cli}
tap=${HOMEBREW_TAP:-carp-dk/homebrew-tap}
formula=Formula/carp.rb

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# The checksums the release published, rather than ones computed here: the
# formula has to describe the bytes people will actually download, and
# SHA256SUMS is the record of what went out.
gh release download "$tag" --repo "$repo" --pattern SHA256SUMS --dir "$work" \
  || fail "$repo has no $tag, or it published no SHA256SUMS"

checksum() {
  local archive sum
  archive="carp-$version-$1.tar.gz"
  sum=$(awk -v want="$archive" '$2 == want { print $1 }' "$work/SHA256SUMS")
  [ -n "$sum" ] || fail "$tag published no $archive"
  printf '%s' "$sum"
}

# Windows is not here on purpose - Homebrew does not run there, and the release
# publishes a .zip for it rather than a tarball.
macos_arm=$(checksum aarch64-apple-darwin)
macos_intel=$(checksum x86_64-apple-darwin)
linux_arm=$(checksum aarch64-unknown-linux-gnu)
linux_intel=$(checksum x86_64-unknown-linux-gnu)

assets="https://github.com/$repo/releases/download/$tag"

# A binary formula rather than one that builds from source: the release has
# already compiled `carp` for all four of these, and asking every machine to
# repeat that - turso, ratatui, the whole tokio tree, under LTO - would turn a
# ten-second install into a ten-minute one.
#
# The heredoc is unquoted so the shell fills in the version, the URLs and the
# checksums. Ruby's own `#{...}` interpolation has no `$` in it, so it survives
# untouched; anything added below that needs a literal `$` or a backtick has to
# be escaped.
#
# `version` is stated rather than left to Homebrew, which would otherwise read
# it out of the file name. `brew audit` calls that redundant; it is worth the
# nit, because a generated formula should say what it is for rather than let a
# heuristic decide, and there are four file names it would have to agree on.
cat > "$work/carp.rb" <<RUBY
# Generated by .github/homebrew/tap.sh in $repo, from the $tag release.
# Do not edit: the next release overwrites this file.
class Carp < Formula
  desc "Client for the Copenhagen Research Platform"
  homepage "https://carp.dk"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$assets/carp-$version-aarch64-apple-darwin.tar.gz"
      sha256 "$macos_arm"
    end

    on_intel do
      url "$assets/carp-$version-x86_64-apple-darwin.tar.gz"
      sha256 "$macos_intel"
    end
  end

  on_linux do
    on_arm do
      url "$assets/carp-$version-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_arm"
    end

    on_intel do
      url "$assets/carp-$version-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_intel"
    end
  end

  def install
    bin.install "carp"
    doc.install "README.md"

    # "carp completions <shell>" writes the script to stdout. Homebrew runs it
    # once per shell it knows about and installs what comes back, so tab
    # completion works from the install rather than from a line in a dotfile.
    generate_completions_from_executable(bin/"carp", "completions")
  end

  test do
    assert_match "carp #{version}", shell_output("#{bin}/carp --version")
    assert_match "studies", shell_output("#{bin}/carp --help")
  end
end
RUBY

# A formula that does not parse would otherwise be found by whoever ran
# `brew install` next. Ruby is on every macOS and every GitHub runner.
if command -v ruby > /dev/null 2>&1; then
  ruby -c "$work/carp.rb" > /dev/null || fail "the generated formula does not parse"
fi

if [ -n "${HOMEBREW_TAP_TOKEN:-}" ]; then
  # `x-access-token` is the user name an app installation token is presented
  # under; the token itself is the password. A personal token works the same
  # way, so this end does not care which it was given.
  origin="https://x-access-token:$HOMEBREW_TAP_TOKEN@github.com/$tap.git"
else
  # Whatever the local credential helper offers - `gh auth setup-git`.
  origin="https://github.com/$tap.git"
fi

git clone --depth 1 --quiet "$origin" "$work/tap" \
  || fail "cannot clone $tap - it has to exist and be writable. See .github/PUBLISHING.md"

# Compared before staging rather than after: an empty tap has no HEAD to diff
# against, and this way a re-run of a release that already updated the tap is
# a no-op instead of an empty commit.
if [ -f "$work/tap/$formula" ] && cmp -s "$work/carp.rb" "$work/tap/$formula"; then
  echo "$tap already points at carp $version"
  exit 0
fi

mkdir -p "$(dirname "$work/tap/$formula")"
cp "$work/carp.rb" "$work/tap/$formula"

# A runner has no identity configured; a maintainer running this by hand does,
# and theirs is the more honest attribution of the two.
if ! git -C "$work/tap" config --get user.email > /dev/null; then
  git -C "$work/tap" config user.name "github-actions[bot]"
  git -C "$work/tap" config user.email \
    "41898282+github-actions[bot]@users.noreply.github.com"
fi

git -C "$work/tap" add "$formula"
git -C "$work/tap" commit --quiet -m "carp $version"
git -C "$work/tap" push --quiet origin HEAD \
  || fail "cannot push to $tap - is the app still installed there, with contents write?"

echo "$tap now installs carp $version"
